@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjcyNTkzMDIsImV4cCI6MTY2ODU1NTMwMiwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDl4ZjN1NnQwMDAwYmF5dGQwYjRsYnp0In0.roRxsW4I9nXK8r1a6RpfXfKknSjCMiYoPDp3TSkceIk
@gustavoToken = yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjcyNTkzODcsImV4cCI6MTY2ODU1NTM4NywiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDl4ZjZlbjAwMDAwYmFwY2pxMWo2YnNuIn0.X_TH24Onw__l_9e9YG7sD5pQVbg9Zs3JgDslZo04K8Y
@andreyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjcyNTk0NzAsImV4cCI6MTY2ODU1NTQ3MCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDl4ZjdmZ3IwMDAyYmFwY211YTJ0ZjU1In0.ErIXb-tDpa88P6I2UM-KjMLVIL_SD24EeqxBH97DIGY
@gustavoId = cl9xf6en00000bapcjq1j6bsn
@andreyId = cl9xf7fgr0002bapcmua2tf55

@rogerioId = cl9u3ihf40000bab64xy1pc42
@fabioId = cl9u3io4e0002bab6fah4dvzs
@fatimaId = cl9u3iu3p0004bab61cm2e9ye

###Login
POST http://localhost:3000/user/auth
Content-Type: application/json

{
    "username": "andrey.rodrigues1",
    "password": "andrey2005"
}


### Get auth
GET http://localhost:3000/user/auth
Content-Type: application/json
Authorization: Bearer {{adminToken}}


###Change password
POST http://localhost:3000/user/change-password
Content-Type: application/json
Authorization: Bearer {{adminToken}}


{   
    "oldPassword": "admin",
    "newPassword": "ad"
}


### Create caregiver
POST http://localhost:3000/caregivers/
Content-Type: application/json
Authorization: Bearer {{adminToken}}


{
    "name": "Andrey Lucas Rodrigues",
    "contact": "(11) 11111-11111",
    "birthdate": "2005-01-01"
}


### Get all caregivers
GET http://localhost:3000/caregivers/
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### Get unique caregiver
GET http://localhost:3000/caregivers/{{andreyId}}
Content-Type: application/json
Authorization: Bearer {{gustavoToken}}


### Update caregiver
POST http://localhost:3000/caregivers/{{gustavoId}}
Content-Type: application/json
Authorization: Bearer {{andreyToken}}

{
    "name": "Gustavo Santos Siqueira",
    "birthdate": "2005-03-20",
    "role": "ADMIN",
    "contact": "(11) 11111-1111"
}


### Delete caregiver
DELETE http://localhost:3000/caregivers/cl9u3ckvt0000b13123
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### Get all patients
GET http://localhost:3000/patients/
Content-Type: application/json
Authorization: Bearer {{adminToken}}



###Create patient
POST http://localhost:3000/patients/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Fátima Aparecido de Melo",
    "birthdate": "1962-01-16",
    "severity": "AAAA",
    "bloodType": "O-",
    "allergies": "Dipirona",
    "contact": "(11) 11111-1111",
    "height": 1.80,
    "medicines": "Glifage",
    "weaknesses": "Diabetes",
    "weight": 70
}


### Get unique patient
GET http://localhost:3000/patients/{{fatimaId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### Update patient
POST http://localhost:3000/patients/{{fatimaId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "name": "Fátima Aparecido de Melo",
    "birthdate": "1962-01-16",
    "severity": "AAAAAA",
    "bloodType": "O-",
    "allergies": "Dipirona",
    "contact": "(11) 11111-1111",
    "height": 1.80,
    "medicines": "Glifage",
    "weaknesses": "Diabetes",
    "weight": 70
}


### Delete patient
DELETE http://localhost:3000/patients/cl9u46niv0000babuti7xq6uv
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### Get all patients from a caregiver
GET http://localhost:3000/caregivers/{{gustavoId}}/patients
Content-Type: application/json
Authorization: Bearer {{gustavoToken}}


### Get all caregivers from a patient
GET http://localhost:3000/patients/{{fatimaId}}/caregivers
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### Get all cares from a patient with a caregiver
GET http://localhost:3000/cares/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "patientId": "{{fabioId}}",
    "caregiverId": "{{gustavoId}}" 
}


###Create care
POST http://localhost:3000/cares/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{   
    "caregiverId": "{{gustavoId}}",
    "patientId": "cl9ugi5df0000ba8wntn4dtok",
    "startTime": "10:00",
    "endTime": "14:00",
    "weekday": 2
}


###Update care
POST http://localhost:3000/cares/cl9ucvr1e0003ba9ojnj0uphn
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "caregiverId": "{{gustavoId}}",
    "patientId": "{{fabioId}}",
    "startTime": "10:00",
    "endTime": "14:00",
    "weekday": 1
}


### Delete care
DELETE http://localhost:3000/cares/cl9ucvr1e0003ba9ojnj0uphn
Content-Type: application/json
Authorization: Bearer {{adminToken}}


###Get all activities from a patient
GET http://localhost:3000/activities/patient/{{fabioId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### Create activity to a patient
POST http://localhost:3000/activities/patient/{{fabioId}}/
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "title": "Parque",
    "description": null,
    "startDatetime": "2022-11-01 14:00",
    "endDatetime": "2022-11-01 16:00"
}


### Get all activities from a caregiver
GET http://localhost:3000/activities/caregiver/{{gustavoId}}
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### Update activity
POST http://localhost:3000/activities/cl9uftrkm0000bafqbuedb9ln
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
    "title": "Parque",
    "description": "Ir dar uma volta no parque",
    "startDatetime": "2022-11-01 09:30",
    "endDatetime": "2022-11-01 21:40"
}


### Delete activity
DELETE http://localhost:3000/activities/cl9uftrkm0000bafqbuedb9ln
Content-Type: application/json
Authorization: Bearer {{adminToken}}


