### Admin: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ
### Caregiver: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMjQsImV4cCI6MTY2Nzg0NjEyNCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlld2F4Z2gwMDA0YmFiaXhoYmU5bGpyIn0.Jnse8IIzV5cr6aGJaa6UaO3sneJFeY-D3MASfr7N1PY

###Login
POST http://localhost:3000/user/auth
Content-Type: application/json

{
    "username": "andrey.rodrigues1",
    "password": "andrey2005"
}


### Get auth
GET http://localhost:3000/user/auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


###Change password
POST http://localhost:3000/user/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


{   
    "oldPassword": "admin123",
    "newPassword": "gustavo123"
}


### Create caregiver
POST http://localhost:3000/caregivers/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


{
    "name": "Mario Junior Silva Paixão",
    "contact": "(11) 11111-11111",
    "birthdate": "2005-01-01"
}


### Get all caregivers
GET http://localhost:3000/caregivers/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


### Get unique caregiver
GET http://localhost:3000/caregivers/cl9lyihgg0000ba4d8hlp0uct
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


### Update caregiver
POST http://localhost:3000/caregivers/cl9ewaxgh0004babixhbe9ljr
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMjQsImV4cCI6MTY2Nzg0NjEyNCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlld2F4Z2gwMDA0YmFiaXhoYmU5bGpyIn0.Jnse8IIzV5cr6aGJaa6UaO3sneJFeY-D3MASfr7N1PY

{
    "name": "Cuidador da Silva Neto Jr.",
    "birthdate": "1990-01-01",
    "role": "CAREGIVER",
    "contact": "(11) 11111-1111"
}


### Delete caregiver
DELETE http://localhost:3000/caregivers/cl9oyanny0000ba802w8es8e9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


### Get all patients
GET http://localhost:3000/patients/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ



###Create patient
POST http://localhost:3000/patients/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ

{
    "name": "Rogério Aparecido de Melo",
    "birthdate": "1962-01-16",
    "severity": "SEVERE",
    "bloodType": "AB+",
    "allergies": "Dipirona",
    "contact": "(11) 11111-1111",
    "height": 1.80,
    "medicines": "Glifage",
    "weaknesses": "Diabetes",
    "weight": 70
}


### Get unique patient
GET http://localhost:3000/patients/cl9opioos0000baelif3vhsno
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY3Mzk3MTQsImV4cCI6MTY2ODAzNTcxNCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlvb2JsY3AwMDAwYmF3Y3A4NGd0ZGt6In0.i69SJNUbx5QcRq9XWLhZKnI7aBcHyyg9UkI-jQ1UZFM


### Update patient
POST http://localhost:3000/patients/cl9opioos0000baelif3vhsno
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY3NDM0NzMsImV4cCI6MTY2ODAzOTQ3MywiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlvbzVnZGwwMDAwYmF6Ym55Z2lqcTB2In0.e6meqSuM5rFR6VJbBeWZd1zMOYCBHwNOOREPApaWIIk

{
    "name": "Marcos Leonardo Santos",
    "birthdate": "1938-07-18",
    "severity": "SEVERE",
    "bloodType": "B+",
    "allergies": "Amendoim\nParecetamol",
    "contact": "(11) 11111-1111",
    "height": 1.66,
    "medicines": "Maleato de Enalapril 20mg\nGlifage Xr 500mg",
    "weaknesses": "Diabetes\nPressão Alta",
    "weight": 61.4
}


### Delete patient
DELETE http://localhost:3000/patients/cl9opioos0000baelif3vhsno
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


### Get all patients from a caregiver
GET http://localhost:3000/caregivers/cl9oo5njt0002bazbp7e7nu7e/patients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


### Get all caregivers from a patient
GET http://localhost:3000/patients/cl9opioos0000baelif3vhsno/caregivers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY1NTAxMDAsImV4cCI6MTY2Nzg0NjEwMCwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlldzgwNmwwMDAwYmFiaW42bmF3Njd1In0.WlAcygJsrIwrcUQbjPuyQt2rvUIAVd2tdPKugn1WTdQ


###Get all activities from a patient
GET http://localhost:3000/activities/patient/cl9q7whqi0000baldmhqyitj1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY4MzkzNTIsImV4cCI6MTY2ODEzNTM1MiwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlvbzVnZGwwMDAwYmF6Ym55Z2lqcTB2In0.AqEu6E_2WKKwi_1T5LlZg4MLMWTLcNlD606DFewaLMI


### Create activity to a patient with a caregiver
POST http://localhost:3000/activities/patient/cl9q7whqi0000baldmhqyitj1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY4MzkzNTIsImV4cCI6MTY2ODEzNTM1MiwiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlvbzVnZGwwMDAwYmF6Ym55Z2lqcTB2In0.AqEu6E_2WKKwi_1T5LlZg4MLMWTLcNlD606DFewaLMI

{
    "title": "Médico",
    "description": "Cardiologista na Av. Paulista 5000",
    "startDatetime": "2022-10-31 08:00",
    "endDatetime": "2022-10-31 18:00"
}


### Get all activities from a caregiver
GET http://localhost:3000/activities/caregiver/cl9oo5gdl0000bazbnygijq0v
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY5MTAwOTMsImV4cCI6MTY2ODIwNjA5MywiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlvbzVnZGwwMDAwYmF6Ym55Z2lqcTB2In0.QruIfBCF0tHfBy11QFcG6R3qqnr_WB_-P2xpEg-DCtM


### Update activity
POST http://localhost:3000/activities/cl9rnkah20000ba5wu12f0ggw
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY5MTAwOTMsImV4cCI6MTY2ODIwNjA5MywiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlvbzVnZGwwMDAwYmF6Ym55Z2lqcTB2In0.QruIfBCF0tHfBy11QFcG6R3qqnr_WB_-P2xpEg-DCtM

{
    "title": "Parque 2",
    "description": null,
    "startDatetime": "2022-10-31 10:30",
    "endDatetime": "2022-10-31 11:40"
}


### Delete activity
DELETE  http://localhost:3000/activities/cl9rnkah20000ba5wu12f0ggw
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjY5MTAwOTMsImV4cCI6MTY2ODIwNjA5MywiaXNzIjoiVGVjaENhcmUiLCJzdWIiOiJjbDlvbzVnZGwwMDAwYmF6Ym55Z2lqcTB2In0.QruIfBCF0tHfBy11QFcG6R3qqnr_WB_-P2xpEg-DCtM